### ISSUE TITLE
dependency on kaln.h

### ISSUE THREAD

**Issue by bwkchee** [CSB5/lofreq#10]
I can't get lofreq to compile against the latest 1.2.x version of samtools.  It seems to depend on kaln.h which is no longer in the samtools 1.2.x repo.

**Comment by andreas-wilm** [comment]
Hi. That was an unnecessary dependency anyway it seems. You can simply remove the corresponding include line from src/lofreq/bam_md_ext.c (fixed in g6f6e173)

Thanks
