### ISSUE TITLE
How to enable lofreq cluster command?

### ISSUE THREAD

**Issue by jwsohn** [CSB5/lofreq#102]
Hi.

Can I ask a question about installing optional commands? I tried to compile lofreq from the source package but the compiled binary does not show `lowfreq cluster` command. How can I enable `lowfreq cluster` command? The extra command of `lowfreq vcfplot` works fine. 

```
$ lofreq cluster
FATAL(lofreq_main.c|main:336): Unrecognized command 'cluster'
```

The `lofreq` command line output is:

```
$ lofreq 

       |             ____|                 
       |       _ \   |     __|  _ \   _` | 
       |      (   |  __|  |     __/  (   | 
      _____| \___/  _|   _|   \___| \__, | 
                                        _| 

Fast and sensitive inference of SNVs and indels

Usage: lofreq <command> [options]

  Main Commands:
    call          : Call variants
    call-parallel : Call variants in parallel
    somatic       : Call somatic variants

  Preprocessing Commands
    viterbi       : Viterbi realignment
    indelqual     : Insert indel qualities
    alnqual       : Insert base and indel alignment qualities

  Other Commands:
    checkref      : Check that reference fasta and BAM file match
    filter        : Filter variants in VCF file
    uniq          : Test whether variants predicted in only one sample really are unique
    plpsummary    : Print pileup summary per position
    vcfset        : VCF set operations
    version       : Print version info

  Samtools Clones:
    faidx         : Create index for fasta file
    index         : Create index for BAM file
    idxstats      : Print stats for indexed BAM file

  Extra Tools (if installed):
    vcfplot       : Plot VCF statistics
```

I tried both the GitHub source and `lofreq_star-2.1.5.tar.gz` source package. PyVCF, Scipy, Numpy, and Matplotlib are all installed.

Thanks,

Jung-woo

**Comment by andreas-wilm** [comment]
Dear Jung-woo,

the cluster command is considered experimental, which is why we never included it in the main set of tools. You can however find the script called `lofreq2_cluster.py` in `src/tools/scripts/` of the source package or [here on Github](https://github.com/CSB5/lofreq/tree/master/src/tools/scripts). It requires [James Casbon's pyvcf](https://github.com/jamescasbon/PyVCF).

Hope this help,
Andreas
