### ISSUE TITLE
Missing Variant with 90% AF

### ISSUE THREAD

**Issue by Admera2020** [CSB5/lofreq#112]
Hello, 

We are using LoFreq to detect mutation in a SARS-Cov2 sample, which is working quite well. However, we are puzzled with one mutation missed by LoFreq. As you can see in IGV the SNP has a frequency over > 90%.  What is strange is that at the exact same position there is a deletion reported with an allele frequency of "0.000294". 

![Sample_igv_POS28048](https://user-images.githubusercontent.com/64089085/112384771-2f9a0100-8cc5-11eb-9977-13984c15dcb4.png)

I am attaching a bam file here
[Sample_POS28048.zip](https://github.com/CSB5/lofreq/files/6200525/Sample_POS28048.zip)

Thank you.

**Comment by Admera2020** [comment]
Actually figured it out. It is due to the strand bias. I used "--no-default-filter" and was able to capture the mutation.

**Comment by andreas-wilm** [comment]
Glad you figured it out
