### ISSUE TITLE
/bin/sh: line 1: 16782 Killed  and  CRITICAL [2021-11-30 08:43:03,767]: Following command failed with status 137

### ISSUE THREAD

**Issue by gchevignon** [CSB5/lofreq#121]
Hello I have those type of error in my Lofreq run:

NFO [2021-11-30 08:42:58,602]: Using 30 threads with following basic args: lofreq call --no-default-filter --call-indels -f /home1/datawork/gchevign/Projet_filtration_ta
ngentielle.dir/08-BCFTools.dir/modified-ref_CA.dir/ONT_ref_Thau_OsHV1_CA.fasta /home1/datawork/gchevign/Projet_filtration_tangentielle.dir/13-LoFreq.dir//lofreq-out.bam

INFO [2021-11-30 08:42:58,661]: Adding 64 commands to mp-pool
/bin/sh: line 1: 16782 Killed                  lofreq call --no-default-filter --call-indels -f /home1/datawork/gchevign/Projet_filtration_tangentielle.dir/08-BCFTools.di
r/modified-ref_CA.dir/ONT_ref_Thau_OsHV1_CA.fasta /home1/datawork/gchevign/Projet_filtration_tangentielle.dir/13-LoFreq.dir//lofreq-out.bam --no-default-filter -r "ONT_Os
HV-1_Thau:85876-89056" -o /dev/shm/pbs.8080705.datarmor0/lofreq2_call_parallelldzmhl7s/27.vcf.gz > /dev/shm/pbs.8080705.datarmor0/lofreq2_call_parallelldzmhl7s/27.log 2>&
1
CRITICAL [2021-11-30 08:43:03,119]: Following command failed with status 137: lofreq call --no-default-filter --call-indels -f /home1/datawork/gchevign/Projet_filtration_
tangentielle.dir/08-BCFTools.dir/modified-ref_CA.dir/ONT_ref_Thau_OsHV1_CA.fasta /home1/datawork/gchevign/Projet_filtration_tangentielle.dir/13-LoFreq.dir//lofreq-out.bam
 --no-default-filter -r "ONT_OsHV-1_Thau:85876-89056" -o /dev/shm/pbs.8080705.datarmor0/lofreq2_call_parallelldzmhl7s/27.vcf.gz > /dev/shm/pbs.8080705.datarmor0/lofreq2_c
all_parallelldzmhl7s/27.log 2>&1

All of the 64 commands have those type of error...

Any suggestion to fix this ?

Best 

Germain

**Comment by andreas-wilm** [comment]
Hi Germain, 137 is usually an out of memory error. Best, Andreas

**Comment by gchevignon** [comment]
Hello Andreas,
I am using my institutional HPC with 30 CPUs and 200Go or 500Go or 1000Go of ram for a 200kb virus with 1500 reads depth ... So I don't think the problem come from an out of memory ...
What do you think ?

**Comment by andreas-wilm** [comment]
Hard to say. It depends how much memory you requested when you submitted the jobs.

**Comment by gchevignon** [comment]
OK 2000Go of Ram fixed it ...
Lot of ram a such a small genome ...
Thanks
Germain

**Comment by andreas-wilm** [comment]
Yeah memory is influenced by coverage not the genome length
