### ISSUE TITLE
Not compiling against htslib 1.2

### ISSUE THREAD

**Issue by ozagordi** [CSB5/lofreq#13]
Hi!
I just noticed that compilation fails when passing a new version of htslib.

The error is (shortened)

```
bam_md_ext.c:54: error: conflicting types for ‘seq_nt16_int’
/home/ozagordi/tmp/htslib-1.2/htslib/hts.h:186: note: previous declaration of     ‘seq_nt16_int’ was here
make[1]: *** [bam_md_ext.o] Error 1
make[1]: Leaving directory `/home/ozagordi/tmp/lofreq/src/lofreq'
```

I managed to compile successfully by following the steps in .travis.yml

Thanks for lofreq!

**Comment by andreas-wilm** [comment]
Hi Osvaldo,

sorry that you had to dig into the travis.yml to fix this. I can't reproduce the problem with the current git version neither with the latest official release though. Could you please tell me which exact commit or tarball you used? 

Thanks,
Andreas

**Comment by ozagordi** [comment]
No problem, it's good for me to get acquainted to Travis, I should put all
my projects under CI.

I see what I might have done wrong: cloning the samtools-1.2 repo does not
give you the HTSlib, see the message here
<https://github.com/samtools/samtools/releases/tag/1.2>. So I cloned it
separately and ran `configure` against this one and not the one within
samtools-1.2.

**Comment by andreas-wilm** [comment]
Oh okay. I made it clear now in the README that it's best to use the htslib version that comes bundled with samtools. 

Thanks for reporting

**Comment by ozagordi** [comment]
Hi Andreas,
I'm afraid I run into the same problem if I try to use samtools and htslib 1.3.

I have a samtools release that I downloaded to build and install samtools with 

    cd /tmp
    wget -nv -O - https://github.com/samtools/samtools/releases/download/1.3/samtools-1.3.tar.bz2 | \
    tar -xj
    cd samtools-1.3 && make -j 8 && make install

Now I downloaded lofreq, libtoolize, bootstrap and 

    ./configure SAMTOOLS=/tmp/samtools-1.3 HTSLIB=/tmp/samtools-1.3/htslib-1.3
    make

runs into the same error

    In file included from bam_md_ext.c:38:0:
    /tmp/samtools-1.3/bam.h:189:28: error: conflicting types for ‘seq_nt16_int’
     #define bam_nt16_nt4_table seq_nt16_int
                                ^

Same story if I download from SourceForge and if I download samtools and htslib separately. If I use samtools 1.1 everything is fine

```
# install lofreq
wget -nv -O - https://github.com/CSB5/lofreq/archive/v2.1.2.tar.gz | tar -xz
cd lofreq-2.1.2
wget -nv -O - http://downloads.sourceforge.net/project/samtools/samtools/1.1/samtools-1.1.tar.bz2 | tar -xj
cd samtools-1.1
make -j 8
cd ..
libtoolize
./bootstrap && ./configure SAMTOOLS=${PWD}/samtools-1.1/ HTSLIB=${PWD}/samtools-1.1/htslib-1.1/ && make -j 8
```

Not sure if it's worth looking into what changed in samtools.

**Comment by andreas-wilm** [comment]
Hi Osvaldo, 
Yes, sorry. You need samtools/htslib<=1.2. Another fix would be to change things such that LoFreq compiles directly against the htslib library as noted by others. I'm not sure when I will get around implementing this. I'll reopen this related bug until then

**Comment by andreas-wilm** [comment]
See #28
