### ISSUE TITLE
subprocess.CalledProcessError: non-zero exit status 1

### ISSUE THREAD

**Issue by balayev1** [CSB5/lofreq#139]
Hello,

Thank you for developing the package LoFreq.

I'm trying to call somatic mutations using 'lofreq somatic' function with LoFreq version 2.1.5. However, I keep receiving the error message:
CRITICAL [2023-10-12 20:11:48,926]: The following command failed with code 1: lofreq call-parallel --pp-threads 16 -d 101000 -f /scratch.global/balay011/WGS_skChordomas_Bai/reference/Homo_sapiens_assembly38.fasta --verbose --no-default-filter -b 1 -l /scratch.global/balay011/WGS_skChordomas_Bai/reference/Homo_sapiens_assembly38_chrs.bed --call-indels -a 0.100000 --use-orphan -B -N -A /scratch.global/balay011/WGS_skChordomas_Bai/SomaticSNV_calling/work/lofreq/samples/462/SRR14097754.bqsr_BD_BI.bam -o /scratch.global/balay011/WGS_skChordomas_Bai/SomaticSNV_calling/work/lofreq/samples/462/normal_relaxed.vcf.gz
CRITICAL [2023-10-12 20:11:48,927]: Received the following on stderr:
CRITICAL [2023-10-12 20:11:48,927]: Somatic SNV caller failed. Exiting

I think the error is coming from the following line in lofreq2_somatic.py file:
subprocess.check_call(cmd, stdout=fh_stdout, stderr=fh_stderr)

Python version: 3.10

Could you please help me to resolve the issue? Thanks.

Kind regards,
Agshin

**Comment by andreas-wilm** [comment]
Could you please try to run the failed command `lofreq call-parallel`... manually and post the output here?

**Comment by balayev1** [comment]
Thank you for your response @andreas-wilm. When I run ` lofreq call-parallel --pp-threads 16 -d 101000 -f /scratch.global/balay011/WGS_skChordomas_Bai/reference/Homo_sapiens_assembly38.fasta --verbose --no-default-filter -b 1 -l /scratch.global/balay011/WGS_skChordomas_Bai/reference/Homo_sapiens_assembly38_chrs.bed --call-indels -a 0.100000 --use-orphan -B -N -A /scratch.global/balay011/WGS_skChordomas_Bai/SomaticSNV_calling/work/lofreq/samples/462/SRR14097754.bqsr_BD_BI.bam -o /scratch.global/balay011/WGS_skChordomas_Bai/SomaticSNV_calling/work/lofreq/samples/462/normal_relaxed.vcf.gz` 
on the command-line interactively, it works without any error. But when I submit through `lofreq somatic`, it crashes. Could you please tell me what may be an issue? Thanks.

**Comment by andreas-wilm** [comment]
Hm, it's possible that your PATH is not set correctly. How was LoFreq installed? With conda or a package manager? If not, what is your PATH environment variable?

**Comment by balayev1** [comment]
That resolved the issue. I'm sorry for bothering you with this.
