### ISSUE TITLE
Possibly unconsistent count of forward/reverse reads

### ISSUE THREAD

**Issue by ozagordi** [CSB5/lofreq#19]
Hi Andreas,
I already anticipated by mail this observation I made. I simulated forward and reverse reads in quite equal amount and the alignment seems to agree. Nevertheless, the counts of the INFO tag DP4 are strange. For example:

    ##fileformat=VCFv4.0
    ##fileDate=20150429
    ##source=lofreq call -f cns.fasta --no-default-filter -r sample_cons_Pol:1-188 -o /tmp/lofreq2_call_parallelKepDFM/0.vcf.gz hq_2_cons_sorted.bam
    ##reference=cns.fasta
    ...
    #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
    sample_cons_Pol 50      .       C       G       85      PASS    DP=1109;AF=0.005410;SB=0;DP4=1103,0,6,0
    sample_cons_Pol 328     .       A       G       8400    PASS    DP=3231;AF=0.100898;SB=0;DP4=2886,9,325,1

Any thought? I'm using

    version: 2.1.2a
    commit: v2.1.2a-92-g6f6e173
    build-date: Apr  9 2015

Thanks!

**Comment by andreas-wilm** [comment]
Hi Osvaldo,

you said these were single end reads, right? So issues with orphans can be ruled out.

What does the following return:

    samtools view hq_2_cons_sorted.bam sample_cons_Pol:50-50 | cut -f 2 | sort | uniq -c

and likewise for the other variant position

    samtools view hq_2_cons_sorted.bam sample_cons_Pol:328-328 | cut -f 2 | sort | uniq -c

Thanks
Andreas

**Comment by ozagordi** [comment]
I see. I checked the overall distribution of F/R reads. There is a bias depending on the location.

    samtools view hq_2_cons_sorted.bam sample_cons_Pol:50-50 | cut -f 2 | sort | uniq -c
       1109 0
    samtools view hq_2_cons_sorted.bam sample_cons_Pol:328-328 | cut -f 2 | sort | uniq -c
       3221 0
       10 16

    samtools view hq_2_cons_sorted.bam sample_cons_Pol:1000-1000 | cut -f 2 | sort | uniq -c
       3283 0
       3306 16
    samtools view hq_2_cons_sorted.bam sample_cons_Pol:2900-2900 | cut -f 2 | sort | uniq -c
       2435 16

Reads were simulated with `wgsim`, it must be an effect of the short reference.
Thanks.
