### ISSUE TITLE
reporting strand bias

### ISSUE THREAD

**Issue by biorelated** [CSB5/lofreq#33]
Lofreq assigns a Phred-scaled score for strand bias. Why use Phred scores? Is it possible to report the raw probability scores? What does it mean when a site has a Phred score SB=0?

**Comment by andreas-wilm** [comment]
Hi George,

phred scores are commonly used in the field to be able to express low error probabilities or p-values as convenient integer. For strand-bias we use Fisher's Exact Test like in samtools and convert the resulting p-values into a Phred score. See https://en.wikipedia.org/wiki/Phred_quality_score for how to convert between phred score and probability.

Andreas
