### ISSUE TITLE
Error while running LoFreq somatic

### ISSUE THREAD

**Issue by abolia** [CSB5/lofreq#36]
Hi, 

I am getting an invalid syntax error, when I try to run lofreq somatic mode.
$lofreq somatic

  File "Reference/Apps/LoFreq/lofreq_star-2.1.2/bin/lofreq2_somatic.py", line 378
    def rlx_to_str(self, sample_type, (num_snv_tests, num_indel_tests)):
                                      ^
SyntaxError: invalid syntax

Can you please help me fix it.

Thanks, 
Ashini

**Comment by andreas-wilm** [comment]
Hi Ashini,

are you running Python3 by any chance? The current Lofreq version supports
Python2.7 only. I have a branch with Python3 support but it needs a bit
more testing.

Andreas

**Comment by abolia** [comment]
Yes, its 3.5 by default. Is there a way I can force Lofreq somatic to use Python 2.7 as I also have that. I can run Lofreq 'call' fine. Its only somatic thats giving me the error. 

Thanks, 
Ashini

**Comment by andreas-wilm** [comment]
Yes, only the call-parallel wrapper, somatic and a few utility commands need Python. Easiest would be to change your shell environment to use Python2.7 by default. That can be achieved by executing:

    export PATH=your-python2.7-directory:$PATH

Let me know if that solved your problem.

Andreas
