### ISSUE TITLE
What does the AF column really mean?

### ISSUE THREAD

**Issue by biorelated** [CSB5/lofreq#37]
With Lofreq, what does the AF column really represent? My assumption is that it is the minority variant allele frequency. It appears to range between 0 and 1, does that mean that a variant at 1.0 frequency is an actual SNP? Is there some documentation on interpreting these outputs? Many thanks and sorry if this is naive.

**Comment by andreas-wilm** [comment]
Hi George, yes you're right: AF is the allele frequency of the called SNP (or indel). And 1.0 means 100% of bases accounted for are the variant base.

**Comment by biorelated** [comment]
Thank you for your response.  So you are saying that if the reference base is A and the alternative is C, then the allele frequency at this position is 1.0. And therefore the choice of the reference is particulary important. Does lofreq perfome a de novo assembly of the reads before calling the variants or does it base its calls squarely on the provided reference?

**Comment by andreas-wilm** [comment]
Hi George,
there used to be an option to call a consensus base first before calling,
but many people abused this, misunderstood it and eventually it became
difficult to support in the code, so we removed it. So yes, it's based on
the reference only.

Your example holds if you only have Cs in the column yes. You usually have
many reads mapping to a particular position. If all of them support a
variant of a particular type then the AF is 100%.

Andreas

On 29 June 2016 at 20:39, George <notifications@github.com> wrote:

> Thank you for your response. So you are saying that if the reference base
> is A and the alternative is C, then the allele frequency at this position
> is 1.0. And therefore the choice of the reference is particulary important.
> Does lofreq perfome a de novo assembly of the reads before calling the
> variants or does it base its calls squarely on the provided reference?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/CSB5/lofreq/issues/37#issuecomment-229343592>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABC5CT8S7dbpEE6VwfAZh4CC_r9-YqVLks5qQmeEgaJpZM4JA5Ke>
> .
>



-- 
Andreas Wilm
andreas.wilm@gmail.com | mail@andreas-wilm.com | 0x7C68FBCC

**Comment by biorelated** [comment]
So the DP4 column may be more important to identify the actual reads and maybe ignore the reference based AF score?

**Comment by andreas-wilm** [comment]
DP4 lists reference and alternate base counts on forward and reverse
strand. It ignores any other alleles/errors at that position, so the allele
frequency derived from DP4 might not correspond 100% with the given AF
value.

Is there something particular you're looking for or trying to do?

Andreas

On 29 June 2016 at 20:53, George <notifications@github.com> wrote:

> So the DP4 column may be more important to identify the actual reads and
> maybe ignore the reference based AF score?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/CSB5/lofreq/issues/37#issuecomment-229346567>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABC5CestEcldeEHKtMrlAnpNL9XpJF_kks5qQmq1gaJpZM4JA5Ke>
> .
>



-- 
Andreas Wilm
andreas.wilm@gmail.com | mail@andreas-wilm.com | 0x7C68FBCC

**Comment by biorelated** [comment]
Yes. I am calling variants on a number of samples and initially I used the same reference across all the samples. The samples were collected at different time points and from different individuals. However I realised that the results might be biased by the choice of reference particularly the AF scores. I would  be happy to discuss this on email and I can provide more details on what I am trying to accomplish.

**Comment by andreas-wilm** [comment]
Using the same reference across all samples is pretty much the only way to
be able to compare across samples. Otherwise you need to call against a
sample specific assembly and then the position don't mean much. Feel free
to discuss <wilma@gis.a-star.edu.sg>

On 29 June 2016 at 21:04, George <notifications@github.com> wrote:

> Yes. I am calling variants on a number of samples and initially I used the
> same reference across all the samples. The samples were collected at
> different time points and from different individuals. However I realised
> that the results might be biased by the choice of reference particularly
> the AF scores. I would be happy to discuss this on email and I can provide
> more details on what I am trying to accomplish.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/CSB5/lofreq/issues/37#issuecomment-229349236>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABC5CespcvYKOLL0SJDhwvJlbOWijXJKks5qQm1KgaJpZM4JA5Ke>
> .
>



-- 
Andreas Wilm
andreas.wilm@gmail.com | mail@andreas-wilm.com | 0x7C68FBCC

**Comment by biorelated** [comment]
Thank you! Sent an email. :)
