### ISSUE TITLE
Error compiling lofreq

### ISSUE THREAD

**Issue by biorelated** [CSB5/lofreq#43]
I am compiling lofreq using this 

```
 ./configure SAMTOOLS=/apps/samtools/1.2.1 HTSLIB=/apps/htslib/1.2.1/ --
prefix=/apps/lofreq/2.1.3
```

And it starts to compile 

```
configure: Configuring LoFreq_Star (version 2.1.3a) for your system...

            |             ____|
            |       _ \   |     __|  _ \   _` |
            |      (   |  __|  |     __/  (   |
           _____| \___/  _|   _|   \___| \__, |
                                             _|

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... /apps/gcc/5.3.0/bin/gcc
checking whether the C compiler works... yes
```
. .... truncated 

But then it lands on this issue. 

```
> checking whether to build with debug information... no
> checking for /apps/samtools/1.2.1/bam.h... no
> configure: error: bam.h not found
```

I get this error against htslib 1.2.1 and 1.3.1 and the same with samtools 1.2.1 and 1.3.1. I am not sure how to resolve this error. What compilation steps do you recommend.

**Comment by andreas-wilm** [comment]
Hey George, the compilation expects the compiled source directory for samtools and htslib, not the installation directory (even though that would be the correct way of doing things). I guess /apps/samtools/1.2.1 doesn't bam.h etc, but just the installed  binaries, right? If you still have the samtools source directory, point LoFreq there. Or just install the binary distribution :)

**Comment by biorelated** [comment]
Thank you @andreas-wilm. I though I would to benefit from the new updates since the last binary release which is as of 2015. Maybe you can compile a binary release for 2.1.3b? you could tag it as beta release. I would also be happy to test it and provide feedback.

**Comment by andreas-wilm** [comment]
Coming soon...In the meantime see #28
