### ISSUE TITLE
The variants of Low frequence 

### ISSUE THREAD

**Issue by Tinalxt** [CSB5/lofreq#45]
How can I call the variants that allele frequence is under 1% ? Is there any parameter can be set?

**Comment by andreas-wilm** [comment]
Hello, LoFreq doesn't filter by allele frequency unless you specifically request it. If you have sufficient and/or high quality variant bases at a certain position their variant quality will be high and you should see that variant.

Andreas

**Comment by Tinalxt** [comment]
I wonder what the smallest variation frequency LoFreq can detect ? Because I have a sample with 8 sites of 1% allele frequence. When I tested this software, I  did not find all of them. Did you have any test? Or is there any parameter can I set to get more variants. Thank you!

**Comment by andreas-wilm** [comment]
Hello, sorry, I have no idea why this has been without a reply for so long. My apologies. Regarding your question:  In the original paper we wetlab-validated variants at 0.5% (and that's when validation gets tricky). There is no theoretical limit as LoFreq's resolution depends on coverage and qualities only. It's likely that your "missed" variants are simply filtered, for example by the strand bias which is applied by default. You can switch default filtering off with the `--no-default-filter` option in `lofreq call`. Andreas
