### ISSUE TITLE
DP and DP4 fields

### ISSUE THREAD

**Issue by abolia** [CSB5/lofreq#49]
Hi Andreas, 

Can you please explain how DP and DP4 fields differ? I know DP is raw depth and DP4 is counts for ref and alt on forward & reverse bases. So, I believe DP4 is subset of raw depth and does not include reads with strand bias. Is that correct? 
We have a variant for which the allele frequency calculated by Lofreq is 3% ( I use -m20 -q 13 and -Q 13) and quality of 290, but when we calculate it from the DP4 counts for ref and alt, it comes out to be 49.19%. IGV also has VAF of 48%, so just wondering how should I go about interpreting these. Should we always calculate the VAF from DP4? 
Moreover, when I run Lofreq with default settings, it calculates VAF as 47.7% and DP4 estimated VAF is still 49% with a quality of 3586. So, definitely the settings change the allele frequency calculation by Lofreq but why is DP4 not affected by this. Can you please help me solve this issue.

Thank you.

**Comment by andreas-wilm** [comment]
Hello,

DP4 values are calculated after filtering and you apply quite a few extra filteres. If you filter extensively, you distort the signal. That's why we suggest to not add extra filters to LoFreq. It's designed to be able to deal with noise.

 Strand-bias applies to variants not bases, so that doesn't affect AF.

Hope that helps,
Andreas

**Comment by abolia** [comment]
Thanks Andreas for the explanation. You said that DP4 values are calculated after filtering, but in my case the AF calculated from DP4 values remains unchanged even when I use filters. With or without filters it is 49.19%. However, AF reported by Lofreq changes based on the filters instead. 

Thank you.

**Comment by andreas-wilm** [comment]
Oh okay. That's how I remembered it. Should have checked the code.

Andreas
