### ISSUE TITLE
Issue when run make 

### ISSUE THREAD

**Issue by WashingtondaSilva** [CSB5/lofreq#52]
Hi there,

I am trying to install lofreq on Ubuntu 16.04 and get this following error msg when run make

washington@Linux:~/lofreq$ make
Making all in src/cdflib90
make[1]: Entering directory '/home/washington/lofreq/src/cdflib90'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/washington/lofreq/src/cdflib90'
Making all in src/uthash
make[1]: Entering directory '/home/washington/lofreq/src/uthash'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/washington/lofreq/src/uthash'
Making all in src/lofreq
make[1]: Entering directory '/home/washington/lofreq/src/lofreq'
gcc -DPACKAGE_NAME=\"LoFreq_Star\" -DPACKAGE_TARNAME=\"lofreq_star\" -DPACKAGE_VERSION=\"2.1.3.1\" -DPACKAGE_STRING=\"LoFreq_Star\ 2.1.3.1\" -DPACKAGE_BUGREPORT=\"wilma@gis.a-star.edu.sg\" -DPACKAGE_URL=\"\" -DGIT_VERSION=\"v2.1.3.1-dirty\" -DPACKAGE=\"lofreq_star\" -DVERSION=\"2.1.3.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DSTDC_HEADERS=1 -DHAVE_PTHREAD_PRIO_INHERIT=1 -DHAVE_PTHREAD=1 -DHAVE_LIBM=1 -DHAVE_LIBZ=1 -DNDEBUG=/\*\*/ -D_USE_KNETFILE=1 -I.    -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -Wall -I../cdflib90/ -I../uthash -I/home/washington/htslib-1.5 -I/home/washington/samtools-1.5  -g -O2 -pthread -MT bam_md_ext.o -MD -MP -MF .deps/bam_md_ext.Tpo -c -o bam_md_ext.o bam_md_ext.c
In file included from bam_md_ext.c:38:0:
/home/washington/samtools-1.5/bam.h:189:28: error: conflicting types for ‘seq_nt16_int’
 #define bam_nt16_nt4_table seq_nt16_int
                            ^
bam_md_ext.c:54:12: note: in expansion of macro ‘bam_nt16_nt4_table’
 const char bam_nt16_nt4_table[] = { 4, 0, 1, 4, 2, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4 };
            ^
In file included from /home/washington/htslib-1.5/htslib/sam.h:31:0,
                 from bam_md_ext.c:37:
/home/washington/htslib-1.5/htslib/hts.h:319:18: note: previous declaration of ‘seq_nt16_int’ was here
 extern const int seq_nt16_int[];
                  ^
In file included from bam_md_ext.c:43:0:
samutils.h:47:14: warning: ‘op_cat_str’ defined but not used [-Wunused-variable]
 static char *op_cat_str[] = {
              ^
Makefile:467: recipe for target 'bam_md_ext.o' failed
make[1]: *** [bam_md_ext.o] Error 1
make[1]: Leaving directory '/home/washington/lofreq/src/lofreq'
Makefile:403: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

can anyone provide and help?

Thank you,

WLD

**Comment by andreas-wilm** [comment]
Hi WLD,

looks like this is is a version mismatch.  You will unfortunately need samtools 1.1 and htslib 1.1 (see "Installation from Source" here: http://csb5.github.io/lofreq/installation/). The two have moved on, but the current LoFreq code still depends on it. I'm trying to get rid of this requirement. The alternative is to install the binary package (see same URL).

Andreas

**Comment by stevendbrown** [comment]
Using samtools 1.7, the error is slightly different but still present for me.

**Comment by andreas-wilm** [comment]
Yes, only version 1.1 will until I've rewritten the code base. Sorry

**Comment by tseemann** [comment]
I can't even locate a `bam.h` in any of the 1.7 samtools or htslib repos!

**Comment by andreas-wilm** [comment]
Yeah, we need to rewrite a few chunks to be able to move with htslib.

**Comment by tseemann** [comment]
@andreas-wilm i managed to make a homebrew recipe to build it from source:

https://github.com/brewsci/homebrew-bio/blob/master/Formula/lofreq.rb

```
brew install brewsci/bio/lofreq
```

**Comment by andreas-wilm** [comment]
Cheers!
