### ISSUE TITLE
VCF sample column

### ISSUE THREAD

**Issue by igordot** [CSB5/lofreq#53]
I've been using LoFreq for a while and haven't had any issues with it. However, recently, I got an error that my VCF was not valid because it did not have a sample column (it stops at `INFO`). Is it possible to add the sample column? If that's not already built in, is it possible to add it somehow with an external tool?

**Comment by andreas-wilm** [comment]
Hi, 

yeah, the SAMPLE column is missing and some downstream application do need this. The next version (we are rewriting LoFreq entirely) will write this natively hopefully. Having said this, there is script contained within LoFreq that does help you with adding a fake sample column: src/tools/scripts/lofreq2_add_fake_gt.py and if you need something more sophisticated you can try tools/scripts/lofreq2_add_sample.py

Hope this helps,
Andreas

**Comment by igordot** [comment]
Thanks for pointing out those files.

With `lofreq2_add_fake_gt.py`, I got a warning that FORMAT 'GT' is not defined in the header, which makes sense because it's not.

With `lofreq2_add_sample.py`, it started running and generating output, but then quickly stopped:
```
WARNING [2017-09-11 21:48:37,193]: Skipping unsupported variant) chr1:761957:A
WARNING [2017-09-11 21:48:37,457]: Skipping unsupported variant) chr1:807302:A
Traceback (most recent call last):
  File "lofreq2_add_sample.py", line 312, in <module>
    main()
  File "lofreq2_add_sample.py", line 307, in main
    add_plp_to_vcf(args.vcf_in, args.vcf_out, args.bams)
  File "lofreq2_add_sample.py", line 264, in add_plp_to_vcf
    sample_data = gen_plp_data(sam_fh, var)
  File "lofreq2_add_sample.py", line 141, in gen_plp_data
    base = aln_read.seq[plp_read.query_position]
TypeError: string indices must be integers, not NoneType
```

Do you know why that may be?

**Comment by andreas-wilm** [comment]
`lofreq2_add_sample.py` is actually overkill for your task and has external dependencies, so I tried to fix `lofreq2_add_fake_gt.py`.  Would you mind to try again with the [latest version](https://github.com/CSB5/lofreq/raw/master/src/tools/scripts/lofreq2_add_fake_gt.py)? Thanks

**Comment by igordot** [comment]
Thanks for the quick fix. `GT` is now defined in the header.

When I edited the header manually before, the VCF was still not valid. I also tried changing `GT` to diploid format (`.` to `./.`) and that didn't work either. That is why I also tried `lofreq2_add_sample.py`.

**Comment by andreas-wilm** [comment]
Okay cool. So the new version is working and I can go ahead and close this?

**Comment by igordot** [comment]
The `lofreq2_add_sample.py` issue still exists, but that seems to be much more complicated. Feel free to close.

**Comment by andreas-wilm** [comment]
Yes I think I better remove that script. It was more a custom solution I wrote for someone. Thanks for the feedback
