### ISSUE TITLE
germline calls for lofreq somatic

### ISSUE THREAD

**Issue by sraorao** [CSB5/lofreq#58]
Hi, 

I am trying to use vcf output from lofreq for input in the [PureCN](https://bioconductor.org/packages/release/bioc/vignettes/PureCN/inst/doc/PureCN.pdf) package. One of the requirements for PureCN is a vcf file that contains both germline and somatic calls in the same VCF. Is this possible at all with lofreq? Or would that be the same as **prefix_tumor_stringent.snvs.vcf.gz**?

Also, I am unable to get germline calls as a separate file either (documentations says "--germline    Also list germline calls in separate file"), using this command:
`lofreq somatic -n normal.sorted.indelqual.bam -t tumour.sorted.indelqual.bam -o output_folder/prefix_ -f hg38.fa -d $DBSNP38 --threads 35 --call-indels --germline`

The files I get with this command are:
prefix_germline.indels.vcf.gz
prefix_germline.indels.vcf.gz.tbi
prefix_normal_relaxed.log
prefix_normal_relaxed.vcf.gz
prefix_normal_relaxed.vcf.gz.tbi
prefix_normal_stringent.indels.vcf.gz
prefix_normal_stringent.indels.vcf.gz.tbi
prefix_normal_stringent.snvs.vcf.gz
prefix_normal_stringent.snvs.vcf.gz.tbi
prefix_somatic_final.indels.vcf.gz
prefix_somatic_final.indels.vcf.gz.tbi
prefix_somatic_final_minus-dbsnp.indels.vcf.gz
prefix_somatic_final_minus-dbsnp.indels.vcf.gz.tbi
prefix_somatic_final_minus-dbsnp.snvs.vcf.gz
prefix_somatic_final_minus-dbsnp.snvs.vcf.gz.tbi
prefix_somatic_final.snvs.vcf.gz
prefix_somatic_final.snvs.vcf.gz.tbi
prefix_somatic_raw.indels.vcf.gz
prefix_somatic_raw.indels.vcf.gz.tbi
prefix_somatic_raw.snvs.vcf.gz
prefix_somatic_raw.snvs.vcf.gz.tbi
prefix_tumor_relaxed.log
prefix_tumor_relaxed.vcf.gz
prefix_tumor_relaxed.vcf.gz.tbi
prefix_tumor_stringent.indels.vcf.gz
prefix_tumor_stringent.indels.vcf.gz.tbi
prefix_tumor_stringent.snvs.vcf.gz
prefix_tumor_stringent.snvs.vcf.gz.tbi

Should I be getting a file named **prefix_germline.snvs.vcf.gz**, as for indels? 

Thank you for your time!

**Comment by andreas-wilm** [comment]
Hi sraorao,

unfortunately LoFreq doesn't produce germline and somatic calls in the same vcf file. I guess this would require some manual bcftools massaging by the user.

Regarding the expected germline calls: if I see this correctly then this is a bug. The file is only created for indels, but not for SNVs. I will fix this ASAP. Here is what you can do in the meantime: Run

    lofreq vcfset -a intersect -1 prefix_normal_relaxed.vcf.gz -2 prefix_tumor_stringent.snvs.vcf.gz -o prefix_germline.snvs.vcf.gz

Sorry about the invonvenience,
Andreas

**Comment by sraorao** [comment]
Thanks Andreas. It turns out, even when I get the germline mutations, PureCN can not read LoFreq's vcf format (requires sample, genotype, AD, etc). I have read elsewhere on this repo that you are working on adding genotype in the next version, so looking forward to that. I guess I will need to look for another solution in the meantime.
