### ISSUE TITLE
region command flag

### ISSUE THREAD

**Issue by zeneofa** [CSB5/lofreq#6]
Hi,

The command help statements for lofreq call mentions:

- Regions
       -r | --region STR            Region in which pileup should be generated [null]
       -l | --bed FILE              List of positions (chr pos) or regions (BED) [null]

How do we pass a single tuple of say, chr pos-start pos-end, to lofreq call? Does this have to be in bed format, or can this be done from the command line (without needing a file)?

**Comment by andreas-wilm** [comment]
As for samtools, i.e. `-r chrom:start-end`. 

I made this clearer in the usage in latest commit in devel branch.

Andreas
