### ISSUE TITLE
it is suitable for  somatic calling without normal  ?

### ISSUE THREAD

**Issue by WinterLi1993** [CSB5/lofreq#60]
HI,
   My data is  target panel sequencing data,  and I just have tumor sample ,no matched normal sample.
so it is OK  for such my case ?? 

thanks !

**Comment by andreas-wilm** [comment]
Hello, let's say the setup itself is a bit suboptimal. There is no LoFreq somatic command that allows you to run this out of the box. If you want to try nevertheless, then you could try to just run `lofreq call` on the tumor sample and subtract dbSNP (or even better a panel of previously sequenced normal samples) from the output.
Andreas

**Comment by WinterLi1993** [comment]
@andreas-wilm 
any options should be added or changed ?

**Comment by andreas-wilm** [comment]
You mean to implement what I said? I would start with the default settings, but this might require some iterations

**Comment by WinterLi1993** [comment]
yeah, could you please give  me some details ,such as  example  commands ?
