### ISSUE TITLE
lofreq installation error ?

### ISSUE THREAD

**Issue by pinninti19** [CSB5/lofreq#61]
Hello
I try to configure with samtools and Hts-lib 1.1 version. Still it showing the same error. How to rectify it.
Thanks for your comments.

**CMD**
./configure SAMTOOLS=/data/Likith/samtools-1.1 HTSLIB=/data/Likith/samtools-1.1/htslib-1.1

checking for /data/Likith/htslib-develop/htslib/hts.h... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
**config.status: error: cannot find input file: `Makefile.in'**

**Comment by andreas-wilm** [comment]
Hello, 

Looks like you checked out the code from github? Then you need to run `libtoolize`(or `glibtoolize`) first and then `bootstrap`. See "Installation from Github" on [the installation website](http://csb5.github.io/lofreq/installation/). It's much easier if you downloaded the source package from the dist folder on Github (see same page) instead. Or use the binary version obviously

Andreas
