### ISSUE TITLE
Can it call variants on tetraploid species?

### ISSUE THREAD

**Issue by afzm** [CSB5/lofreq#66]

**Comment by andreas-wilm** [comment]
Sure. LoFreq doesn't assume any ploidy level. In an ideal world you would see LoFreq reporting allele frequencies of 25% 50%, 75% and 100% only

Andreas

**Comment by afzm** [comment]
Thank you very much for answering, does that means that it writes tetraploid genotype (0/0/0/0 form) in the VCF file?

**Comment by andreas-wilm** [comment]
Ah no. Lofreq writes no genotype information at all!
