### ISSUE TITLE
LofreqSomatic not calling indel which was called by Lofreq and other callers

### ISSUE THREAD

**Issue by stevekm** [CSB5/lofreq#82]
Hi, we are having an issue where an indel was called by Lofreq, Manta, Strelka, and MuTect2, but it was not called by LofreqSomatic. We are having difficulties understanding why LofreqSomatic did not call this indel. The indel can be seen here clearly in this IGV snapshot:

(tumor sample on top, matched normal sample on bottom)
![chr7_55242464_55242465 copy](https://user-images.githubusercontent.com/10505524/66257944-58df6e00-e76d-11e9-9f58-b4ecd1b090ac.png)

Here is the variant as reported by the other callers:

LoFreq:
```
chr7	55242464	.	AGGAATTAAGAGAAGC	A	8187	PASS	DP=1622;AF=0.191122;SB=0;DP4=666,688,151,159;INDEL;HRUN=2
```

Manta:
```
chr7	55242464	MantaDEL:4744:0:0:1:0:0	AGGAATTAAGAGAAGC	A	.	.	END=55242479;SVTYPE=DEL;SVLEN=-15;CIGAR=1M15D;UPSTREAM_PAIR_COUNT=0;DOWNSTREAM_PAIR_COUNT=0;PAIR_COUNT=0
```

Strelka:
```
chr7	55242464	.	AGGAATTAAGAGAAGC	A	.	PASS	SOMATIC;QSI=789;TQSI=1;NT=ref;QSI_NT=3070;TQSI_NT=1;SGT=ref->het;MQ=59.99;MQ0=0;RU=GGAATTAAGAGAAGC;RC=1;IC=0;IHP=3;SomaticEVS=16.34	DP:DP2:TAR:TIR:TOR:DP50:FDP50:SUBDP50:BCN50	960:960:1007,1016:0,0:14,11:827.03:2.75:0.00:0.00	1674:1674:1333,1348:339,340:80,69:1439.73:1.64:0.00:0.00
```

GATK HaplotypeCaller
```
chr7	55242464	.	AGGAATTAAGAGAAGC	A	3754.73	.	AC=1;AF=0.500;AN=2;BaseQRankSum=-0.912;ClippingRankSum=0.000;DP=1737;ExcessHet=3.0103;FS=0.673;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.000;QD=2.19;ReadPosRankSum=5.727;SOR=0.768	GT:AD:DP:GQ:PL	0/1:1387,328:1715:99:3792,0,57107
```

GATK MuTect2
```
chr7	55242464	rs121913421	AGGAATTAAGAGAAGC	A	.	PASS	DB;ECNT=1;HCNT=24;MAX_ED=.;MIN_ED=.;NLOD=182.27;TLOD=678.72	GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1	0/1:1380,351:0.193:161:190:.:43287,10906:696:684	0/0:1010,0:0.00:0:0:.:35085,0:524:486
```

Any idea why this would have been missed or not reported by LofreqSomatic? The command we are using is:

```
    lofreq somatic \
    -n "${normalBam}" \
    -t "${tumorBam}" \
    -f "${ref_fasta}" \
    --threads 16 \
    -o "${lofreq_prefix}" \
    -d "${dbsnp_ref_vcf_gz}" \
    -l "${targets_bed}"
```

Using Lofreq version 2.1.2 installed by conda.

**Comment by andreas-wilm** [comment]
Hi Stephen,

LoFreq Somatic (which was never published and is sort of experimental) uses a subtractive approach: it calls variants with stringent parameters in the tumor sample and with relaxed parameters in the normal sample. It then subtracts everything it sees in the normal from the tumor. I would inspect the normal vcf file that its also produces to see whether it saw this variant there.

Andreas

**Comment by stevekm** [comment]
Well the solution was simple in this case, I forgot to include the flag `--call-indels`. This was kind of surprising, because regular Lofreq outputs indels without any extra flags, and LofreqSomatic still outputs .vcf files labeled "indels" even without the flag but the .vcf files are empty.
