### ISSUE TITLE
effect of capping MQ on reads with MQ 255

### ISSUE THREAD

**Issue by wm75** [CSB5/lofreq#84]
Not sure if understand the behavior of lofreq call correctly here, but I think that:

with `--no-mq` set to anything lower than 255 mapping qualities of 255 will be capped to the new limit *before* the SNP caller sees them? If so, then the effort to turn mqs of 255 into -1 before calculating error probabilities would be futile?

Would that mean that if one wants to cap mapping qualities, one should first remove reads with MQ 255 in a preprocessing step?

**Comment by andreas-wilm** [comment]
LoFreq joins multiple qualities i.e error probabilities into one merged quality, which is used for calling. These are by default: mapping quality, alignment quality and base/indel quality. See also [this section in the draft LoFreq3 documentation](https://github.com/andreas-wilm/lofreq3#pileup-1). You can choose to ignore mapping (`--no-mq`) or alignment quality (`--no-baq/--no-idaq`), but this should be very rarely needed unless the corresponding values are entirely off or wrong.

**Comment by wm75** [comment]
Sorry to bother you on this one, but your reply did not really answer my question.
If I understand the actual code correctly, then e.g. with --max-mq 254, lofreq would:
1. convert MQs of 255 to 254
2. happily use those 254 values to calculate joined error probabilities (unless --no-mq is in use)

while without --max-mq it would ignore reads with MQs of 255 entirely.

Correct?

**Comment by andreas-wilm** [comment]
Ah sorry. Yes and no:

- yes: `--max-mq` is for capping, i.e. `--max-mq 60` will set all MQs>60 to 60 (should probably be called `--cap-mq`) 
- no: reads with MQ 255 will not be ignored. A value of 255 is according to the SAM standard undefined. So in that case the quality isn't used during the quality merging, but the read itself is still used

Hope this explain the behaviour better
Andreas
