### ISSUE TITLE
BD/BI tags are missing (no indels were called)

### ISSUE THREAD

**Issue by sleyn** [CSB5/lofreq#88]
Hi!

I've used the BaseRecalibrator from GATK (v 4.1.4.1), but  no indels were called with `lofreq call-parallel --call-indel ...`. After my investigation it seems that the new GATK do not insert BD and BI tags to the SAM format. I did not find the specific statement from the GATK team of abandoning them except some mention few years ago that they have this intention.

Could you check - am I doing something wrong or GATK BaseRecalibrator should be removed from the best practices. 

Thanks,
Semion

**Comment by andreas-wilm** [comment]
Hi Semion, thanks for reporting this. Yes confirmed. GATK's BQSR (at least with 4.1.4.1) doesn't produce any BI/BD tags anymore. I'm not sure why they dropped it, nor can I find out when it happened. So `lofreq indelqual` is the way to go. I'll update the docs accordingly.


Andreas
