### ISSUE TITLE
Handling of soft-clipped bases

### ISSUE THREAD

**Issue by rspreafico-vir** [CSB5/lofreq#94]
Hi there

I am trying to confirm that soft-clipped bases are not used by LoFreq. I checked paper and documentation but couldn't find an answer. The motivation is to confirm that soft clipping primers from hundreds of overlapping amplicons (e.g. using [primerclip](https://github.com/swiftbiosciences/primerclip)) will truly hide the primer bases from LoFreq. Variant callers that use local realignment will rescue soft-clipped bases, but I believe LoFreq will not (which would be great for my use case).

Thanks
Roberto

**Comment by andreas-wilm** [comment]
Hi Roberto,

LoFreq will ignore soft clipped bases. The viterbi realigner won't touch
them either.

Best,
Andreas

**Comment by rspreafico-vir** [comment]
Thanks for confirming @andreas-wilm !
