### ISSUE TITLE
Confirm that --max-depth is per-base coverage

### ISSUE THREAD

**Issue by rspreafico-vir** [CSB5/lofreq#97]
Hi there,

just wanted to confirm that `--max-depth` caps coverage at per-base level, as opposed to read level. I have a dataset with pretty uneven coverage (by design, because of the way the assay works) and some of the low-coverage sites seem not to get as much coverage as I anticipated, and I wonder whether that is because I am capping depth.

Thank you!

**Comment by andreas-wilm** [comment]
Hi Roberto, yes correct, it's base level coverage, however, after read level filtering.

**Comment by rspreafico-vir** [comment]
Thank you Andreas!
